### PR TITLE
Generate reference links for painless API

### PR DESCRIPTION
**Pull request by nik9000**
Adds "Appending B. Painless API Reference", a reference of all classes and methods available from painless. Removes links to java packages because they contain methods that we don't expose and don't contain methods that we do expose (the ones in Augmentation). Instead this generates a list of every class and every exposed method using the same type information available to the interpreter/compiler/whatever-we-call-it. From there you can jump to the relevant docs.

Right now you build all the asciidoc files by running
```
gradle generatePainlessApi
```

You can also run it in an IDE safely if you pass the path to the directory in which to generate the docs as the first parameter. It'll blow away the entire directory an recreate it from scratch so be careful.

And then you can build the docs by running something like:
```
../docs/build_docs.pl --out ../built_docs/ --doc docs/reference/index.asciidoc --open
```

That is, if you have checked out https://github.com/elastic/docs in `../docs`. Wait a minute or two and your browser will pop open in with all of Elasticsearch's reference documentation. If you go to `http://localhost:8000/painless-api-reference.html` you can see this list. Or you can get there by following the links to `Modules` and `Scripting` and `painless` and then clicking the link in the paragraphs below titled `Appendix B. Painless API Reference`.

I like having these in asciidoc because we can deep link to them from the rest of the guide with constructs like `<<painless-api-reference-Object-hashCode-0>>` and `<<painless-api-reference->>` and we get link checking. Then the only brittle link maintenance bit is the link generation for javadoc. Which sucks. But I think it is important that we reference the methods directly so they are easy to find.

WIP for a bunch of reasons:
1. I'm not 100% set on the linking strategy. It is certainly easier than trying to extract that javadoc of the method I'm linking to. And it should be safe from a licensing perspective. But it is much less convenient.
1. It isn't clear if we should generate the documentation and check it in or if we should generate it when we're generating the docs to publish. Either way works and we can do one for now and switch if we like. The process of generating the documentation is pretty much instant if you include it in another gradle execution.
1. We don't publish Javadoc so the Elasticsearch docs links to a place that republishes. And the versions are all wrong. And Painless's javadoc isn't available but we need to publish at least some of it to make this linking strategy work.
1. It may be worth moving this out of src/test/java and into src/tool/java or something. I don't know how to do that off hand so I'm not going to do it unless someone tells me it is important.
1. I don't really like the way the `(java 9)` links look. I think they are important to have. Or it is important to have something like them.

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @nik9000 - i tried building your painless_links branch but I get the following when I do gradle generatePainlessApi:

```
:modules:lang-painless:compileJava
Full recompilation is required because 'PainlessLexer.java' was changed. Analysis took 3.541 secs.
/Users/clinton/workspace/elasticsearch/modules/lang-painless/src/main/java/org/elasticsearch/painless/Definition.java:507: error: reference not found
    /** Collection of all simple types. Used by {@link PainlessDocGenerator} to generate an API reference. */
                                                       ^
1 error
```

**Comment by nik9000** [comment]
@clintongormley weird. I pushed a patch that I'm sure works locally.

**Comment by clintongormley** [comment]
Tried again and now this:

```
Full recompilation is required because 'elasticsearch-6.0.0-alpha1-SNAPSHOT.jar' was changed. Analysis took 3.63 secs.
/Users/clinton/workspace/elasticsearch/modules/lang-painless/src/main/java/org/elasticsearch/painless/Definition.java:507: error: reference not found
    /** Collection of all simple types. Used by {@link PainlessDocGenerator} to generate an API reference. */
                                                       ^
1 error
:modules:lang-painless:compileJava FAILED
```

**Comment by nik9000** [comment]
Sorry! I was able to reproduce by cleaning. Without clean I wasn't getting the failure.... I pushed a fix for it.

**Comment by jdconrad** [comment]
@nik9000 I think the feature is great and definitely needed.  I'm not overly concerned about the code at this point because I know it's still a WIP.  Will be super happy to have this in once you're happy with the code.

**Pull request closed without merging**
